namespace Operis_API.Modules.Operations.Contracts;

public sealed record CreateAccessReviewRequest(string ScopeType, string ScopeRef, string ReviewCycle, string? ReviewedBy);
public sealed record UpdateAccessReviewRequest(string ScopeType, string ScopeRef, string ReviewCycle, string? ReviewedBy, string Status);
public sealed record ApproveAccessReviewRequest(string Decision, string DecisionRationale);
public sealed record CreateSecurityReviewRequest(string ScopeType, string ScopeRef, string ControlsReviewed, string? FindingsSummary, string Status);
public sealed record UpdateSecurityReviewRequest(string ScopeType, string ScopeRef, string ControlsReviewed, string? FindingsSummary, string Status);
public sealed record CreateExternalDependencyRequest(string Name, string DependencyType, Guid? SupplierId, string OwnerUserId, string Criticality, DateTimeOffset? ReviewDueAt, string Status);
public sealed record UpdateExternalDependencyRequest(string Name, string DependencyType, Guid? SupplierId, string OwnerUserId, string Criticality, DateTimeOffset? ReviewDueAt, string Status);
public sealed record CreateConfigurationAuditRequest(string ScopeRef, DateTimeOffset PlannedAt, string Status, int FindingCount);
public sealed record CreateSupplierRequest(string Name, string SupplierType, string OwnerUserId, string Criticality, DateTimeOffset? ReviewDueAt, string Status);
public sealed record UpdateSupplierRequest(string Name, string SupplierType, string OwnerUserId, string Criticality, DateTimeOffset? ReviewDueAt, string Status);
public sealed record CreateSupplierAgreementRequest(Guid SupplierId, string AgreementType, DateOnly? EffectiveFrom, DateOnly? EffectiveTo, string? SlaTerms, string? EvidenceRef, string Status);
public sealed record UpdateSupplierAgreementRequest(Guid SupplierId, string AgreementType, DateOnly? EffectiveFrom, DateOnly? EffectiveTo, string? SlaTerms, string? EvidenceRef, string Status);
public sealed record CreateAccessRecertificationRequest(string ScopeType, string ScopeRef, DateTimeOffset PlannedAt, string ReviewOwnerUserId, IReadOnlyList<string>? SubjectUserIds, string? ExceptionNotes);
public sealed record UpdateAccessRecertificationRequest(string ScopeType, string ScopeRef, DateTimeOffset PlannedAt, string ReviewOwnerUserId, string Status, IReadOnlyList<string>? SubjectUserIds, string? ExceptionNotes);
public sealed record AddAccessRecertificationDecisionRequest(string SubjectUserId, string Decision, string? Reason);
public sealed record CreateSecurityIncidentRequest(Guid? ProjectId, string Code, string Title, string Severity, DateTimeOffset ReportedAt, string OwnerUserId, string Status, string? ResolutionSummary);
public sealed record UpdateSecurityIncidentRequest(Guid? ProjectId, string Code, string Title, string Severity, DateTimeOffset ReportedAt, string OwnerUserId, string Status, string? ResolutionSummary);
public sealed record CreateVulnerabilityRequest(string AssetRef, string Title, string Severity, DateTimeOffset IdentifiedAt, DateTimeOffset? PatchDueAt, string OwnerUserId, string Status, string? VerificationSummary);
public sealed record UpdateVulnerabilityRequest(string AssetRef, string Title, string Severity, DateTimeOffset IdentifiedAt, DateTimeOffset? PatchDueAt, string OwnerUserId, string Status, string? VerificationSummary);
public sealed record CreateSecretRotationRequest(string SecretScope, DateTimeOffset PlannedAt, DateTimeOffset? RotatedAt, string? VerifiedBy, DateTimeOffset? VerifiedAt, string Status);
public sealed record UpdateSecretRotationRequest(string SecretScope, DateTimeOffset PlannedAt, DateTimeOffset? RotatedAt, string? VerifiedBy, DateTimeOffset? VerifiedAt, string Status);
public sealed record CreatePrivilegedAccessEventRequest(string RequestedBy, string? ApprovedBy, string? UsedBy, DateTimeOffset RequestedAt, DateTimeOffset? ApprovedAt, DateTimeOffset? UsedAt, DateTimeOffset? ReviewedAt, string Status, string Reason);
public sealed record UpdatePrivilegedAccessEventRequest(string RequestedBy, string? ApprovedBy, string? UsedBy, DateTimeOffset RequestedAt, DateTimeOffset? ApprovedAt, DateTimeOffset? UsedAt, DateTimeOffset? ReviewedAt, string Status, string Reason);
public sealed record CreateClassificationPolicyRequest(string PolicyCode, string ClassificationLevel, string Scope, string Status, string? HandlingRule);
public sealed record UpdateClassificationPolicyRequest(string PolicyCode, string ClassificationLevel, string Scope, string Status, string? HandlingRule);

public sealed record AccessReviewResponse(Guid Id, string ScopeType, string ScopeRef, string ReviewCycle, string? ReviewedBy, string Status, string? Decision, string? DecisionRationale, DateTimeOffset CreatedAt, DateTimeOffset? UpdatedAt);
public sealed record SecurityReviewResponse(Guid Id, string ScopeType, string ScopeRef, string ControlsReviewed, string? FindingsSummary, string Status, DateTimeOffset CreatedAt, DateTimeOffset? UpdatedAt);
public sealed record ExternalDependencyResponse(Guid Id, string Name, string DependencyType, Guid? SupplierId, string? SupplierName, string OwnerUserId, string Criticality, string Status, DateTimeOffset? ReviewDueAt, DateTimeOffset CreatedAt, DateTimeOffset? UpdatedAt);
public sealed record ConfigurationAuditResponse(Guid Id, string ScopeRef, DateTimeOffset PlannedAt, string Status, int FindingCount, DateTimeOffset CreatedAt, DateTimeOffset? UpdatedAt);
public sealed record SupplierResponse(Guid Id, string Name, string SupplierType, string OwnerUserId, string Criticality, string Status, DateTimeOffset? ReviewDueAt, int ActiveAgreementCount, DateTimeOffset CreatedAt, DateTimeOffset? UpdatedAt);
public sealed record SupplierAgreementResponse(Guid Id, Guid SupplierId, string SupplierName, string AgreementType, DateOnly EffectiveFrom, DateOnly? EffectiveTo, string SlaTerms, string EvidenceRef, string Status, DateTimeOffset CreatedAt, DateTimeOffset? UpdatedAt);
public sealed record AccessRecertificationDecisionResponse(Guid Id, Guid ScheduleId, string SubjectUserId, string Decision, string Reason, string DecidedBy, DateTimeOffset DecidedAt);
public sealed record AccessRecertificationResponse(Guid Id, string ScopeType, string ScopeRef, DateTimeOffset PlannedAt, string ReviewOwnerUserId, string Status, IReadOnlyList<string> SubjectUserIds, IReadOnlyList<AccessRecertificationDecisionResponse> Decisions, string? ExceptionNotes, int CompletedCount, int PendingCount, DateTimeOffset CreatedAt, DateTimeOffset? UpdatedAt, DateTimeOffset? CompletedAt);
public sealed record SecurityIncidentResponse(Guid Id, Guid? ProjectId, string? ProjectName, string Code, string Title, string Severity, DateTimeOffset ReportedAt, string OwnerUserId, string Status, string? ResolutionSummary, DateTimeOffset CreatedAt, DateTimeOffset? UpdatedAt);
public sealed record VulnerabilityResponse(Guid Id, string AssetRef, string Title, string Severity, DateTimeOffset IdentifiedAt, DateTimeOffset? PatchDueAt, string OwnerUserId, string Status, string? VerificationSummary, DateTimeOffset CreatedAt, DateTimeOffset? UpdatedAt);
public sealed record SecretRotationResponse(Guid Id, string SecretScope, DateTimeOffset PlannedAt, DateTimeOffset? RotatedAt, string? VerifiedBy, DateTimeOffset? VerifiedAt, string Status, DateTimeOffset CreatedAt, DateTimeOffset? UpdatedAt);
public sealed record PrivilegedAccessEventResponse(Guid Id, string RequestedBy, string? ApprovedBy, string? UsedBy, DateTimeOffset RequestedAt, DateTimeOffset? ApprovedAt, DateTimeOffset? UsedAt, DateTimeOffset? ReviewedAt, string Status, string Reason, DateTimeOffset CreatedAt, DateTimeOffset? UpdatedAt);
public sealed record ClassificationPolicyResponse(Guid Id, string PolicyCode, string ClassificationLevel, string Scope, string Status, string? HandlingRule, DateTimeOffset CreatedAt, DateTimeOffset? UpdatedAt);
