parent=keycloak.v2
import=common/keycloak
styles=css/styles.css
scripts=js/ui-controls.js

# Optional brand text displayed by some templates/messages
kcLogoIdP-operis=Operis

# App links (used in login.ftl)
oiAppBaseUrl=http://localhost:5173
