namespace Operis_API.Modules.Audits.Contracts;

public sealed record AuditLogListItem(
    Guid Id,
    DateTimeOffset OccurredAt,
    string Module,
    string Action,
    string EntityType,
    string? EntityId,
    string? ActorUserId,
    string? ActorEmail,
    string? ActorDisplayName,
    string Status,
    string? HttpMethod,
    string? RequestPath);

public sealed record AuditLogResponse(
    Guid Id,
    DateTimeOffset OccurredAt,
    string Module,
    string Action,
    string EntityType,
    string? EntityId,
    string ActorType,
    string? ActorUserId,
    string? ActorEmail,
    string? ActorDisplayName,
    Guid? DepartmentId,
    string? TenantId,
    string? RequestId,
    string? TraceId,
    string? CorrelationId,
    string? HttpMethod,
    string? RequestPath,
    string? IpAddress,
    string? UserAgent,
    string Status,
    int? StatusCode,
    string? ErrorCode,
    string? ErrorMessage,
    string? Reason,
    string Source,
    string? BeforeJson,
    string? AfterJson,
    string? ChangesJson,
    string? MetadataJson,
    bool IsSensitive,
    string? RetentionClass);
