const allPermissions = [
  "admin.permission_matrix.read",
  "admin.permission_matrix.apply",
  "admin.settings.read",
  "admin.settings.manage",
  "users.read",
  "users.create",
  "users.update",
  "users.delete",
  "users.invite",
  "users.registrations.review",
  "master_data.read",
  "master_data.permanent_org.manage",
  "master_data.project_structures.manage",
  "projects.read",
  "projects.manage",
  "projects.roles.manage",
  "projects.members.manage",
  "projects.evidence.read",
  "projects.evidence.export",
  "projects.compliance.read",
  "projects.templates.manage",
  "activity_logs.read",
  "activity_logs.export",
  "audit_logs.read",
  "audit_logs.export",
  "documents.read",
  "documents.upload",
  "documents.versions.manage",
  "documents.publish",
  "documents.draft.delete",
  "documents.deactivate",
  "workflows.read",
  "workflows.definitions.manage",
  "governance.process_library.read",
  "governance.process_library.manage",
  "governance.qa_checklist.read",
  "governance.qa_checklist.manage",
  "governance.project_plan.read",
  "governance.project_plan.manage",
  "governance.project_plan.approve",
  "governance.stakeholder.read",
  "governance.stakeholder.manage",
  "governance.tailoring.read",
  "governance.tailoring.manage",
  "governance.tailoring.approve",
  "requirements.read",
  "requirements.manage",
  "requirements.approve",
  "requirements.baseline",
  "requirements.traceability.manage",
  "change_control.read",
  "change_control.manage",
  "change_control.approve",
  "change_control.configuration.read",
  "change_control.configuration.manage",
  "change_control.baselines.manage",
  "change_control.baselines.approve",
  "change_control.emergency_override",
  "risks.read",
  "risks.manage",
  "risks.sensitive.read",
  "notifications.read",
] as const;

export const permissions = {
  admin: {
    permissionMatrixRead: "admin.permission_matrix.read",
    permissionMatrixApply: "admin.permission_matrix.apply",
    settingsRead: "admin.settings.read",
    settingsManage: "admin.settings.manage",
  },
  users: {
    read: "users.read",
    create: "users.create",
    update: "users.update",
    delete: "users.delete",
    invite: "users.invite",
    reviewRegistrations: "users.registrations.review",
  },
  masterData: {
    read: "master_data.read",
    managePermanentOrg: "master_data.permanent_org.manage",
    manageProjectStructures: "master_data.project_structures.manage",
  },
  projects: {
    read: "projects.read",
    manage: "projects.manage",
    manageRoles: "projects.roles.manage",
    manageMembers: "projects.members.manage",
    readEvidence: "projects.evidence.read",
    exportEvidence: "projects.evidence.export",
    readCompliance: "projects.compliance.read",
    manageTemplates: "projects.templates.manage",
  },
  activityLogs: {
    read: "activity_logs.read",
    export: "activity_logs.export",
  },
  auditLogs: {
    read: "audit_logs.read",
    export: "audit_logs.export",
  },
  documents: {
    read: "documents.read",
    upload: "documents.upload",
    manageVersions: "documents.versions.manage",
    publish: "documents.publish",
    deleteDraft: "documents.draft.delete",
    deactivate: "documents.deactivate",
  },
  workflows: {
    read: "workflows.read",
    manageDefinitions: "workflows.definitions.manage",
  },
  governance: {
    processLibraryRead: "governance.process_library.read",
    processLibraryManage: "governance.process_library.manage",
    qaChecklistRead: "governance.qa_checklist.read",
    qaChecklistManage: "governance.qa_checklist.manage",
    projectPlanRead: "governance.project_plan.read",
    projectPlanManage: "governance.project_plan.manage",
    projectPlanApprove: "governance.project_plan.approve",
    stakeholderRead: "governance.stakeholder.read",
    stakeholderManage: "governance.stakeholder.manage",
    tailoringRead: "governance.tailoring.read",
    tailoringManage: "governance.tailoring.manage",
    tailoringApprove: "governance.tailoring.approve",
  },
  requirements: {
    read: "requirements.read",
    manage: "requirements.manage",
    approve: "requirements.approve",
    baseline: "requirements.baseline",
    manageTraceability: "requirements.traceability.manage",
  },
  changeControl: {
    read: "change_control.read",
    manage: "change_control.manage",
    approve: "change_control.approve",
    readConfiguration: "change_control.configuration.read",
    manageConfiguration: "change_control.configuration.manage",
    manageBaselines: "change_control.baselines.manage",
    approveBaselines: "change_control.baselines.approve",
    emergencyOverride: "change_control.emergency_override",
  },
  risks: {
    read: "risks.read",
    manage: "risks.manage",
    readSensitive: "risks.sensitive.read",
  },
  notifications: {
    read: "notifications.read",
  },
} as const;

export type Permission = (typeof allPermissions)[number];

const rolePermissionMap: Record<string, readonly Permission[]> = {
  "operis:super_admin": allPermissions,
  operis_super_admin: allPermissions,
  "operis:system_admin": [
    permissions.admin.permissionMatrixRead,
    permissions.admin.permissionMatrixApply,
    permissions.admin.settingsRead,
    permissions.admin.settingsManage,
    permissions.users.read,
    permissions.users.create,
    permissions.users.update,
    permissions.users.delete,
    permissions.users.invite,
    permissions.users.reviewRegistrations,
    permissions.masterData.read,
    permissions.masterData.managePermanentOrg,
    permissions.masterData.manageProjectStructures,
    permissions.projects.read,
    permissions.projects.manage,
    permissions.projects.manageRoles,
    permissions.projects.manageMembers,
    permissions.projects.readEvidence,
    permissions.projects.exportEvidence,
    permissions.projects.readCompliance,
    permissions.projects.manageTemplates,
    permissions.activityLogs.read,
    permissions.activityLogs.export,
    permissions.auditLogs.read,
    permissions.auditLogs.export,
    permissions.documents.read,
    permissions.documents.upload,
    permissions.documents.manageVersions,
    permissions.documents.publish,
    permissions.documents.deleteDraft,
    permissions.documents.deactivate,
    permissions.workflows.read,
    permissions.workflows.manageDefinitions,
    permissions.governance.processLibraryRead,
    permissions.governance.processLibraryManage,
    permissions.governance.qaChecklistRead,
    permissions.governance.qaChecklistManage,
    permissions.governance.projectPlanRead,
    permissions.governance.projectPlanManage,
    permissions.governance.projectPlanApprove,
    permissions.governance.stakeholderRead,
    permissions.governance.stakeholderManage,
    permissions.governance.tailoringRead,
    permissions.governance.tailoringManage,
    permissions.governance.tailoringApprove,
    permissions.requirements.read,
    permissions.requirements.manage,
    permissions.requirements.approve,
    permissions.requirements.baseline,
    permissions.requirements.manageTraceability,
    permissions.changeControl.read,
    permissions.changeControl.manage,
    permissions.changeControl.approve,
    permissions.changeControl.readConfiguration,
    permissions.changeControl.manageConfiguration,
    permissions.changeControl.manageBaselines,
    permissions.changeControl.approveBaselines,
    permissions.changeControl.emergencyOverride,
    permissions.risks.read,
    permissions.risks.manage,
    permissions.risks.readSensitive,
    permissions.notifications.read,
  ],
  operis_system_admin: [
    permissions.admin.permissionMatrixRead,
    permissions.admin.permissionMatrixApply,
    permissions.admin.settingsRead,
    permissions.admin.settingsManage,
    permissions.users.read,
    permissions.users.create,
    permissions.users.update,
    permissions.users.delete,
    permissions.users.invite,
    permissions.users.reviewRegistrations,
    permissions.masterData.read,
    permissions.masterData.managePermanentOrg,
    permissions.masterData.manageProjectStructures,
    permissions.projects.read,
    permissions.projects.manage,
    permissions.projects.manageRoles,
    permissions.projects.manageMembers,
    permissions.projects.readEvidence,
    permissions.projects.exportEvidence,
    permissions.projects.readCompliance,
    permissions.projects.manageTemplates,
    permissions.activityLogs.read,
    permissions.activityLogs.export,
    permissions.auditLogs.read,
    permissions.auditLogs.export,
    permissions.documents.read,
    permissions.workflows.read,
    permissions.workflows.manageDefinitions,
    permissions.governance.processLibraryRead,
    permissions.governance.processLibraryManage,
    permissions.governance.qaChecklistRead,
    permissions.governance.qaChecklistManage,
    permissions.governance.projectPlanRead,
    permissions.governance.projectPlanManage,
    permissions.governance.projectPlanApprove,
    permissions.governance.stakeholderRead,
    permissions.governance.stakeholderManage,
    permissions.governance.tailoringRead,
    permissions.governance.tailoringManage,
    permissions.governance.tailoringApprove,
    permissions.requirements.read,
    permissions.changeControl.read,
    permissions.changeControl.readConfiguration,
    permissions.risks.read,
    permissions.risks.readSensitive,
    permissions.notifications.read,
  ],
  "operis:audit_auditor": [
    permissions.activityLogs.read,
    permissions.activityLogs.export,
    permissions.auditLogs.read,
    permissions.auditLogs.export,
    permissions.projects.readEvidence,
    permissions.projects.readCompliance,
    permissions.documents.read,
    permissions.workflows.read,
    permissions.requirements.read,
    permissions.risks.read,
    permissions.risks.readSensitive,
    permissions.notifications.read,
  ],
  "operis:documents_owner": [
    permissions.documents.read,
    permissions.documents.upload,
    permissions.documents.manageVersions,
    permissions.documents.publish,
    permissions.documents.deleteDraft,
    permissions.documents.deactivate,
    permissions.changeControl.readConfiguration,
    permissions.changeControl.manageConfiguration,
    permissions.risks.read,
    permissions.notifications.read,
  ],
  "operis:documents_reviewer": [permissions.documents.read, permissions.notifications.read],
  "operis:workflows_approver": [permissions.workflows.read, permissions.notifications.read],
  "operis:workflows_department_manager": [permissions.workflows.read, permissions.notifications.read],
  "operis:employee_viewer": [permissions.workflows.read, permissions.notifications.read],
  "operis:ops_support": [permissions.admin.settingsRead, permissions.activityLogs.read, permissions.notifications.read],
  "operis:compliance_admin": [
    permissions.governance.processLibraryRead,
    permissions.governance.processLibraryManage,
    permissions.governance.qaChecklistRead,
    permissions.governance.qaChecklistManage,
    permissions.governance.projectPlanRead,
    permissions.governance.projectPlanApprove,
    permissions.governance.stakeholderRead,
    permissions.governance.tailoringRead,
    permissions.governance.tailoringApprove,
    permissions.requirements.read,
    permissions.requirements.approve,
    permissions.requirements.baseline,
    permissions.changeControl.read,
    permissions.changeControl.approve,
    permissions.changeControl.readConfiguration,
    permissions.changeControl.approveBaselines,
    permissions.changeControl.emergencyOverride,
    permissions.risks.read,
    permissions.risks.manage,
    permissions.risks.readSensitive,
  ],
  "operis:pm": [
    permissions.governance.processLibraryRead,
    permissions.governance.qaChecklistRead,
    permissions.governance.projectPlanRead,
    permissions.governance.projectPlanManage,
    permissions.governance.stakeholderRead,
    permissions.governance.stakeholderManage,
    permissions.governance.tailoringRead,
    permissions.governance.tailoringManage,
    permissions.requirements.read,
    permissions.requirements.manage,
    permissions.requirements.baseline,
    permissions.requirements.manageTraceability,
    permissions.changeControl.read,
    permissions.changeControl.manage,
    permissions.changeControl.readConfiguration,
    permissions.changeControl.manageBaselines,
    permissions.risks.read,
    permissions.risks.manage,
    permissions.risks.readSensitive,
  ],
  "operis:ba": [
    permissions.governance.processLibraryRead,
    permissions.governance.qaChecklistRead,
    permissions.governance.stakeholderRead,
    permissions.requirements.read,
    permissions.requirements.manage,
    permissions.requirements.manageTraceability,
    permissions.changeControl.read,
    permissions.changeControl.manage,
    permissions.changeControl.readConfiguration,
    permissions.risks.read,
    permissions.risks.manage,
  ],
  "operis:qa": [
    permissions.governance.qaChecklistRead,
    permissions.governance.projectPlanRead,
    permissions.requirements.read,
    permissions.changeControl.read,
    permissions.changeControl.readConfiguration,
    permissions.risks.read,
  ],
  "operis:approver": [
    permissions.governance.qaChecklistRead,
    permissions.governance.projectPlanRead,
    permissions.governance.projectPlanApprove,
    permissions.governance.tailoringRead,
    permissions.governance.tailoringApprove,
    permissions.requirements.read,
    permissions.requirements.approve,
    permissions.requirements.baseline,
    permissions.changeControl.read,
    permissions.changeControl.approve,
    permissions.changeControl.readConfiguration,
    permissions.changeControl.approveBaselines,
    permissions.risks.read,
    permissions.risks.readSensitive,
  ],
  "operis:requirements_manager": [
    permissions.requirements.read,
    permissions.requirements.manage,
    permissions.requirements.manageTraceability,
  ],
  "operis:requirements_approver": [
    permissions.requirements.read,
    permissions.requirements.approve,
    permissions.requirements.baseline,
  ],
  "operis:change_manager": [
    permissions.changeControl.read,
    permissions.changeControl.manage,
    permissions.changeControl.readConfiguration,
    permissions.changeControl.manageBaselines,
  ],
  "operis:risk_manager": [
    permissions.risks.read,
    permissions.risks.manage,
    permissions.risks.readSensitive,
  ],
  "operis:risk_viewer": [
    permissions.risks.read,
  ],
  "operis:configuration_controller": [
    permissions.changeControl.readConfiguration,
    permissions.changeControl.manageConfiguration,
  ],
};

export function getPermissionLabel(permission: Permission) {
  return {
    [permissions.admin.permissionMatrixRead]: "Read Permission Matrix",
    [permissions.admin.permissionMatrixApply]: "Apply Permission Matrix",
    [permissions.admin.settingsRead]: "Read System Settings",
    [permissions.admin.settingsManage]: "Manage System Settings",
    [permissions.users.read]: "Read Users",
    [permissions.users.create]: "Create Users",
    [permissions.users.update]: "Update Users",
    [permissions.users.delete]: "Delete Users",
    [permissions.users.invite]: "Invite Users",
    [permissions.users.reviewRegistrations]: "Review Registrations",
    [permissions.masterData.read]: "Read Master Data",
    [permissions.masterData.managePermanentOrg]: "Manage Permanent Org",
    [permissions.masterData.manageProjectStructures]: "Manage Project Structures",
    [permissions.projects.read]: "Read Projects",
    [permissions.projects.manage]: "Manage Projects",
    [permissions.projects.manageRoles]: "Manage Project Roles",
    [permissions.projects.manageMembers]: "Manage Project Members",
    [permissions.projects.readEvidence]: "Read Project Evidence",
    [permissions.projects.exportEvidence]: "Export Project Evidence",
    [permissions.projects.readCompliance]: "Read Project Compliance",
    [permissions.projects.manageTemplates]: "Manage Project Templates",
    [permissions.activityLogs.read]: "Read Activity Logs",
    [permissions.activityLogs.export]: "Export Activity Logs",
    [permissions.auditLogs.read]: "Read Audit Logs",
    [permissions.auditLogs.export]: "Export Audit Logs",
    [permissions.documents.read]: "Read Documents",
    [permissions.documents.upload]: "Upload Documents",
    [permissions.documents.manageVersions]: "Manage Document Versions",
    [permissions.documents.publish]: "Publish Documents",
    [permissions.documents.deleteDraft]: "Delete Draft Documents",
    [permissions.documents.deactivate]: "Deactivate Documents",
    [permissions.workflows.read]: "Read Workflows",
    [permissions.workflows.manageDefinitions]: "Manage Workflow Definitions",
    [permissions.governance.processLibraryRead]: "Read Process Library",
    [permissions.governance.processLibraryManage]: "Manage Process Library",
    [permissions.governance.qaChecklistRead]: "Read QA Checklists",
    [permissions.governance.qaChecklistManage]: "Manage QA Checklists",
    [permissions.governance.projectPlanRead]: "Read Project Plans",
    [permissions.governance.projectPlanManage]: "Manage Project Plans",
    [permissions.governance.projectPlanApprove]: "Approve Project Plans",
    [permissions.governance.stakeholderRead]: "Read Stakeholders",
    [permissions.governance.stakeholderManage]: "Manage Stakeholders",
    [permissions.governance.tailoringRead]: "Read Tailoring Records",
    [permissions.governance.tailoringManage]: "Manage Tailoring Records",
    [permissions.governance.tailoringApprove]: "Approve Tailoring Records",
    [permissions.requirements.read]: "Read Requirements",
    [permissions.requirements.manage]: "Manage Requirements",
    [permissions.requirements.approve]: "Approve Requirements",
    [permissions.requirements.baseline]: "Baseline Requirements",
    [permissions.requirements.manageTraceability]: "Manage Requirement Traceability",
    [permissions.changeControl.read]: "Read Change Requests",
    [permissions.changeControl.manage]: "Manage Change Requests",
    [permissions.changeControl.approve]: "Approve Change Requests",
    [permissions.changeControl.readConfiguration]: "Read Configuration Items",
    [permissions.changeControl.manageConfiguration]: "Manage Configuration Items",
    [permissions.changeControl.manageBaselines]: "Manage Baselines",
    [permissions.changeControl.approveBaselines]: "Approve Baselines",
    [permissions.changeControl.emergencyOverride]: "Emergency Override Change Control",
    [permissions.risks.read]: "Read Risks and Issues",
    [permissions.risks.manage]: "Manage Risks and Issues",
    [permissions.risks.readSensitive]: "Read Sensitive Issues",
    [permissions.notifications.read]: "Read Notifications",
  }[permission];
}

export function getPermissionsForRoles(roles: string[]): Permission[] {
  const resolved = new Set<Permission>();
  for (const role of roles) {
    for (const permission of rolePermissionMap[role] ?? []) {
      resolved.add(permission);
    }
  }

  return Array.from(resolved);
}
