const allPermissions = [
  "admin.permission_matrix.read",
  "admin.permission_matrix.apply",
  "admin.settings.read",
  "admin.settings.manage",
  "users.read",
  "users.create",
  "users.update",
  "users.delete",
  "users.invite",
  "users.registrations.review",
  "master_data.read",
  "master_data.permanent_org.manage",
  "master_data.project_structures.manage",
  "projects.read",
  "projects.manage",
  "projects.roles.manage",
  "projects.members.manage",
  "projects.evidence.read",
  "projects.evidence.export",
  "projects.compliance.read",
  "projects.templates.manage",
  "activity_logs.read",
  "activity_logs.export",
  "audit_logs.read",
  "audit_logs.export",
  "documents.read",
  "documents.upload",
  "documents.versions.manage",
  "documents.publish",
  "documents.draft.delete",
  "documents.deactivate",
  "workflows.read",
  "workflows.definitions.manage",
  "notifications.read",
] as const;

export const permissions = {
  admin: {
    permissionMatrixRead: "admin.permission_matrix.read",
    permissionMatrixApply: "admin.permission_matrix.apply",
    settingsRead: "admin.settings.read",
    settingsManage: "admin.settings.manage",
  },
  users: {
    read: "users.read",
    create: "users.create",
    update: "users.update",
    delete: "users.delete",
    invite: "users.invite",
    reviewRegistrations: "users.registrations.review",
  },
  masterData: {
    read: "master_data.read",
    managePermanentOrg: "master_data.permanent_org.manage",
    manageProjectStructures: "master_data.project_structures.manage",
  },
  projects: {
    read: "projects.read",
    manage: "projects.manage",
    manageRoles: "projects.roles.manage",
    manageMembers: "projects.members.manage",
    readEvidence: "projects.evidence.read",
    exportEvidence: "projects.evidence.export",
    readCompliance: "projects.compliance.read",
    manageTemplates: "projects.templates.manage",
  },
  activityLogs: {
    read: "activity_logs.read",
    export: "activity_logs.export",
  },
  auditLogs: {
    read: "audit_logs.read",
    export: "audit_logs.export",
  },
  documents: {
    read: "documents.read",
    upload: "documents.upload",
    manageVersions: "documents.versions.manage",
    publish: "documents.publish",
    deleteDraft: "documents.draft.delete",
    deactivate: "documents.deactivate",
  },
  workflows: {
    read: "workflows.read",
    manageDefinitions: "workflows.definitions.manage",
  },
  notifications: {
    read: "notifications.read",
  },
} as const;

export type Permission = (typeof allPermissions)[number];

const rolePermissionMap: Record<string, readonly Permission[]> = {
  "operis:super_admin": allPermissions,
  operis_super_admin: allPermissions,
  "operis:system_admin": [
    permissions.admin.permissionMatrixRead,
    permissions.admin.permissionMatrixApply,
    permissions.admin.settingsRead,
    permissions.admin.settingsManage,
    permissions.users.read,
    permissions.users.create,
    permissions.users.update,
    permissions.users.delete,
    permissions.users.invite,
    permissions.users.reviewRegistrations,
    permissions.masterData.read,
    permissions.masterData.managePermanentOrg,
    permissions.masterData.manageProjectStructures,
    permissions.projects.read,
    permissions.projects.manage,
    permissions.projects.manageRoles,
    permissions.projects.manageMembers,
    permissions.projects.readEvidence,
    permissions.projects.exportEvidence,
    permissions.projects.readCompliance,
    permissions.projects.manageTemplates,
    permissions.activityLogs.read,
    permissions.activityLogs.export,
    permissions.auditLogs.read,
    permissions.auditLogs.export,
    permissions.documents.read,
    permissions.documents.upload,
    permissions.documents.manageVersions,
    permissions.documents.publish,
    permissions.documents.deleteDraft,
    permissions.documents.deactivate,
    permissions.workflows.read,
    permissions.workflows.manageDefinitions,
    permissions.notifications.read,
  ],
  operis_system_admin: [
    permissions.admin.permissionMatrixRead,
    permissions.admin.permissionMatrixApply,
    permissions.admin.settingsRead,
    permissions.admin.settingsManage,
    permissions.users.read,
    permissions.users.create,
    permissions.users.update,
    permissions.users.delete,
    permissions.users.invite,
    permissions.users.reviewRegistrations,
    permissions.masterData.read,
    permissions.masterData.managePermanentOrg,
    permissions.masterData.manageProjectStructures,
    permissions.projects.read,
    permissions.projects.manage,
    permissions.projects.manageRoles,
    permissions.projects.manageMembers,
    permissions.projects.readEvidence,
    permissions.projects.exportEvidence,
    permissions.projects.readCompliance,
    permissions.projects.manageTemplates,
    permissions.activityLogs.read,
    permissions.activityLogs.export,
    permissions.auditLogs.read,
    permissions.auditLogs.export,
    permissions.documents.read,
    permissions.workflows.read,
    permissions.workflows.manageDefinitions,
    permissions.notifications.read,
  ],
  "operis:audit_auditor": [
    permissions.activityLogs.read,
    permissions.activityLogs.export,
    permissions.auditLogs.read,
    permissions.auditLogs.export,
    permissions.projects.readEvidence,
    permissions.projects.readCompliance,
    permissions.documents.read,
    permissions.workflows.read,
    permissions.notifications.read,
  ],
  "operis:documents_owner": [
    permissions.documents.read,
    permissions.documents.upload,
    permissions.documents.manageVersions,
    permissions.documents.publish,
    permissions.documents.deleteDraft,
    permissions.documents.deactivate,
    permissions.notifications.read,
  ],
  "operis:documents_reviewer": [permissions.documents.read, permissions.notifications.read],
  "operis:workflows_approver": [permissions.workflows.read, permissions.notifications.read],
  "operis:workflows_department_manager": [permissions.workflows.read, permissions.notifications.read],
  "operis:employee_viewer": [permissions.workflows.read, permissions.notifications.read],
  "operis:ops_support": [permissions.admin.settingsRead, permissions.activityLogs.read, permissions.notifications.read],
};

export function getPermissionLabel(permission: Permission) {
  return {
    [permissions.admin.permissionMatrixRead]: "Read Permission Matrix",
    [permissions.admin.permissionMatrixApply]: "Apply Permission Matrix",
    [permissions.admin.settingsRead]: "Read System Settings",
    [permissions.admin.settingsManage]: "Manage System Settings",
    [permissions.users.read]: "Read Users",
    [permissions.users.create]: "Create Users",
    [permissions.users.update]: "Update Users",
    [permissions.users.delete]: "Delete Users",
    [permissions.users.invite]: "Invite Users",
    [permissions.users.reviewRegistrations]: "Review Registrations",
    [permissions.masterData.read]: "Read Master Data",
    [permissions.masterData.managePermanentOrg]: "Manage Permanent Org",
    [permissions.masterData.manageProjectStructures]: "Manage Project Structures",
    [permissions.projects.read]: "Read Projects",
    [permissions.projects.manage]: "Manage Projects",
    [permissions.projects.manageRoles]: "Manage Project Roles",
    [permissions.projects.manageMembers]: "Manage Project Members",
    [permissions.projects.readEvidence]: "Read Project Evidence",
    [permissions.projects.exportEvidence]: "Export Project Evidence",
    [permissions.projects.readCompliance]: "Read Project Compliance",
    [permissions.projects.manageTemplates]: "Manage Project Templates",
    [permissions.activityLogs.read]: "Read Activity Logs",
    [permissions.activityLogs.export]: "Export Activity Logs",
    [permissions.auditLogs.read]: "Read Audit Logs",
    [permissions.auditLogs.export]: "Export Audit Logs",
    [permissions.documents.read]: "Read Documents",
    [permissions.documents.upload]: "Upload Documents",
    [permissions.documents.manageVersions]: "Manage Document Versions",
    [permissions.documents.publish]: "Publish Documents",
    [permissions.documents.deleteDraft]: "Delete Draft Documents",
    [permissions.documents.deactivate]: "Deactivate Documents",
    [permissions.workflows.read]: "Read Workflows",
    [permissions.workflows.manageDefinitions]: "Manage Workflow Definitions",
    [permissions.notifications.read]: "Read Notifications",
  }[permission];
}

export function getPermissionsForRoles(roles: string[]): Permission[] {
  const resolved = new Set<Permission>();
  for (const role of roles) {
    for (const permission of rolePermissionMap[role] ?? []) {
      resolved.add(permission);
    }
  }

  return Array.from(resolved);
}
